// Copyright 2026 Alan Beebe (radiocli.com). All Rights Reserved.
// Author: Alan Beebe
// Created: 8/2/2026

package colors

// This file is the screen map: where every area of every layout sits.
//
// It is a table rather than a reading because these positions are the
// firmware's, not the user's. Nothing in the scanner's menus moves an area, so
// asking the scanner would be asking a question whose answer cannot change,
// and it would cost ten seconds and a stopped scan to be told what is written
// here. Anything redrawing the scanner's screen wants this per frame, which a
// menu walk could never serve.
//
// Read off an SDS150 on firmware 1.00.37, 2026-08-04, by stepping through each
// layout editor and recording the span the scanner draws in reverse video for
// the selected area. The geometry of the editor screen and of the live
// scanning screen match line for line, which is what makes the approach work.
//
// A firmware that moved something would make this silently wrong, drawing the
// screen with the right colors in the wrong places and reporting nothing. That
// is what "colors --verify-positions" is for: it walks the editors again and
// reports anything that disagrees. The test suite runs it under -writes.
//
// The five soft key areas along the bottom row are deliberately absent. That
// row is drawn entirely in reverse video at all times, so the editor cannot
// say which part of it belongs to the selected area. They are read off the
// live row instead, where the three runs of reverse video are the three keys.
// See softKeys.

// positions maps each layout to its areas.
var positions = map[string]map[string]position{
	"simple-conventional": {
		"Func":           {Line: 0, Column: 0, Length: 2, Height: 1},
		"Option_1":       {Line: 0, Column: 2, Length: 6, Height: 1},
		"Option_2":       {Line: 0, Column: 8, Length: 6, Height: 1},
		"Option_3":       {Line: 0, Column: 14, Length: 6, Height: 1},
		"Option_4":       {Line: 0, Column: 20, Length: 6, Height: 1},
		"Signal_meter":   {Line: 0, Column: 26, Length: 2, Height: 1},
		"Battery":        {Line: 0, Column: 28, Length: 2, Height: 1},
		"Space_0":        {Line: 1, Column: 0, Length: 2, Height: 1},
		"Option_5":       {Line: 1, Column: 2, Length: 6, Height: 1},
		"Option_6":       {Line: 1, Column: 8, Length: 6, Height: 1},
		"Option_7":       {Line: 1, Column: 14, Length: 6, Height: 1},
		"Option_8":       {Line: 1, Column: 20, Length: 6, Height: 1},
		"Key_lock":       {Line: 1, Column: 26, Length: 2, Height: 1},
		"Direction":      {Line: 1, Column: 28, Length: 2, Height: 1},
		"System_name":    {Line: 2, Column: 0, Length: 24, Height: 2},
		"System_option":  {Line: 4, Column: 0, Length: 26, Height: 1},
		"System_avoid":   {Line: 4, Column: 26, Length: 4, Height: 1},
		"Dept_name":      {Line: 5, Column: 0, Length: 24, Height: 2},
		"Dept_option":    {Line: 7, Column: 0, Length: 26, Height: 1},
		"Dept_avoid":     {Line: 7, Column: 26, Length: 4, Height: 1},
		"Channel_name":   {Line: 8, Column: 0, Length: 24, Height: 2},
		"Channel_option": {Line: 10, Column: 0, Length: 26, Height: 1},
		"Channel_avoid":  {Line: 10, Column: 26, Length: 4, Height: 1},
		"Option_A":       {Line: 11, Column: 0, Length: 16, Height: 1},
		"Option_B":       {Line: 11, Column: 16, Length: 14, Height: 1},
		"Icon_1":         {Line: 12, Column: 0, Length: 3, Height: 1},
		"Icon_2":         {Line: 12, Column: 3, Length: 3, Height: 1},
		"Icon_3":         {Line: 12, Column: 6, Length: 3, Height: 1},
		"Icon_4":         {Line: 12, Column: 9, Length: 3, Height: 1},
		"Icon_5":         {Line: 12, Column: 12, Length: 3, Height: 1},
		"Icon_6":         {Line: 12, Column: 15, Length: 3, Height: 1},
		"Icon_7":         {Line: 12, Column: 18, Length: 3, Height: 1},
		"Icon_8":         {Line: 12, Column: 21, Length: 3, Height: 1},
		"Icon_9":         {Line: 12, Column: 24, Length: 3, Height: 1},
		"Icon_a":         {Line: 12, Column: 27, Length: 3, Height: 1},
	},
	"simple-trunk": {
		"Func":           {Line: 0, Column: 0, Length: 2, Height: 1},
		"Option_1":       {Line: 0, Column: 2, Length: 6, Height: 1},
		"Option_2":       {Line: 0, Column: 8, Length: 6, Height: 1},
		"Option_3":       {Line: 0, Column: 14, Length: 6, Height: 1},
		"Option_4":       {Line: 0, Column: 20, Length: 6, Height: 1},
		"Signal_meter":   {Line: 0, Column: 26, Length: 2, Height: 1},
		"Battery":        {Line: 0, Column: 28, Length: 2, Height: 1},
		"Space_0":        {Line: 1, Column: 0, Length: 2, Height: 1},
		"Option_5":       {Line: 1, Column: 2, Length: 6, Height: 1},
		"Option_6":       {Line: 1, Column: 8, Length: 6, Height: 1},
		"Option_7":       {Line: 1, Column: 14, Length: 6, Height: 1},
		"Option_8":       {Line: 1, Column: 20, Length: 6, Height: 1},
		"Key_lock":       {Line: 1, Column: 26, Length: 2, Height: 1},
		"Direction":      {Line: 1, Column: 28, Length: 2, Height: 1},
		"System_name":    {Line: 2, Column: 0, Length: 24, Height: 2},
		"System_option":  {Line: 4, Column: 0, Length: 26, Height: 1},
		"System_avoid":   {Line: 4, Column: 26, Length: 4, Height: 1},
		"Dept_name":      {Line: 5, Column: 0, Length: 24, Height: 2},
		"Dept_option":    {Line: 7, Column: 0, Length: 26, Height: 1},
		"Dept_avoid":     {Line: 7, Column: 26, Length: 4, Height: 1},
		"Channel_name":   {Line: 8, Column: 0, Length: 24, Height: 2},
		"Channel_option": {Line: 10, Column: 0, Length: 26, Height: 1},
		"Channel_avoid":  {Line: 10, Column: 26, Length: 4, Height: 1},
		"Option_A":       {Line: 11, Column: 0, Length: 16, Height: 1},
		"Option_B":       {Line: 11, Column: 16, Length: 14, Height: 1},
		"Icon_1":         {Line: 12, Column: 0, Length: 3, Height: 1},
		"Icon_2":         {Line: 12, Column: 3, Length: 3, Height: 1},
		"Icon_3":         {Line: 12, Column: 6, Length: 3, Height: 1},
		"Icon_4":         {Line: 12, Column: 9, Length: 3, Height: 1},
		"Icon_5":         {Line: 12, Column: 12, Length: 3, Height: 1},
		"Icon_6":         {Line: 12, Column: 15, Length: 3, Height: 1},
		"Icon_7":         {Line: 12, Column: 18, Length: 3, Height: 1},
		"Icon_8":         {Line: 12, Column: 21, Length: 3, Height: 1},
		"Icon_9":         {Line: 12, Column: 24, Length: 3, Height: 1},
		"Icon_a":         {Line: 12, Column: 27, Length: 3, Height: 1},
	},
	"detail-conventional": {
		"Func":           {Line: 0, Column: 0, Length: 2, Height: 1},
		"Option_1":       {Line: 0, Column: 2, Length: 6, Height: 1},
		"Option_2":       {Line: 0, Column: 8, Length: 6, Height: 1},
		"Option_3":       {Line: 0, Column: 14, Length: 6, Height: 1},
		"Option_4":       {Line: 0, Column: 20, Length: 6, Height: 1},
		"Signal_meter":   {Line: 0, Column: 26, Length: 2, Height: 1},
		"Battery":        {Line: 0, Column: 28, Length: 2, Height: 1},
		"Info_area_1":    {Line: 1, Column: 0, Length: 14, Height: 1},
		"Option_7":       {Line: 1, Column: 14, Length: 6, Height: 1},
		"Option_8":       {Line: 1, Column: 20, Length: 6, Height: 1},
		"Key_lock":       {Line: 1, Column: 26, Length: 2, Height: 1},
		"Direction":      {Line: 1, Column: 28, Length: 2, Height: 1},
		"Info_area_2":    {Line: 2, Column: 0, Length: 16, Height: 1},
		"Option_C_1":     {Line: 2, Column: 16, Length: 14, Height: 1},
		"Info_area_3":    {Line: 3, Column: 0, Length: 16, Height: 1},
		"Option_C_2":     {Line: 3, Column: 16, Length: 14, Height: 1},
		"System_name":    {Line: 4, Column: 0, Length: 24, Height: 1},
		"System_option":  {Line: 5, Column: 0, Length: 26, Height: 1},
		"System_avoid":   {Line: 5, Column: 26, Length: 4, Height: 1},
		"Dept_name":      {Line: 6, Column: 0, Length: 24, Height: 1},
		"Dept_option":    {Line: 7, Column: 0, Length: 26, Height: 1},
		"Dept_avoid":     {Line: 7, Column: 26, Length: 4, Height: 1},
		"Channel_name":   {Line: 8, Column: 0, Length: 24, Height: 1},
		"Channel_option": {Line: 9, Column: 0, Length: 26, Height: 1},
		"Channel_avoid":  {Line: 9, Column: 26, Length: 4, Height: 1},
		"Option_A_1":     {Line: 10, Column: 0, Length: 16, Height: 1},
		"Option_B_1":     {Line: 10, Column: 16, Length: 14, Height: 1},
		"Option_A_2":     {Line: 11, Column: 0, Length: 16, Height: 1},
		"Option_B_2":     {Line: 11, Column: 16, Length: 14, Height: 1},
		"Option_A_3":     {Line: 12, Column: 0, Length: 16, Height: 1},
		"Option_B_3":     {Line: 12, Column: 16, Length: 14, Height: 1},
		"Option_A_4":     {Line: 13, Column: 0, Length: 16, Height: 1},
		"Option_B_4":     {Line: 13, Column: 16, Length: 14, Height: 1},
		"Option_A_5":     {Line: 14, Column: 0, Length: 16, Height: 1},
		"Option_B_5":     {Line: 14, Column: 16, Length: 14, Height: 1},
		"Icon_1":         {Line: 15, Column: 0, Length: 3, Height: 1},
		"Icon_2":         {Line: 15, Column: 3, Length: 3, Height: 1},
		"Icon_3":         {Line: 15, Column: 6, Length: 3, Height: 1},
		"Icon_4":         {Line: 15, Column: 9, Length: 3, Height: 1},
		"Icon_5":         {Line: 15, Column: 12, Length: 3, Height: 1},
		"Icon_6":         {Line: 15, Column: 15, Length: 3, Height: 1},
		"Icon_7":         {Line: 15, Column: 18, Length: 3, Height: 1},
		"Icon_8":         {Line: 15, Column: 21, Length: 3, Height: 1},
		"Icon_9":         {Line: 15, Column: 24, Length: 3, Height: 1},
		"Icon_a":         {Line: 15, Column: 27, Length: 3, Height: 1},
	},
	"detail-trunk": {
		"Func":           {Line: 0, Column: 0, Length: 2, Height: 1},
		"Option_1":       {Line: 0, Column: 2, Length: 6, Height: 1},
		"Option_2":       {Line: 0, Column: 8, Length: 6, Height: 1},
		"Option_3":       {Line: 0, Column: 14, Length: 6, Height: 1},
		"Option_4":       {Line: 0, Column: 20, Length: 6, Height: 1},
		"Signal_meter":   {Line: 0, Column: 26, Length: 2, Height: 1},
		"Battery":        {Line: 0, Column: 28, Length: 2, Height: 1},
		"Info_area_1":    {Line: 1, Column: 0, Length: 14, Height: 1},
		"Option_7":       {Line: 1, Column: 14, Length: 6, Height: 1},
		"Option_8":       {Line: 1, Column: 20, Length: 6, Height: 1},
		"Key_lock":       {Line: 1, Column: 26, Length: 2, Height: 1},
		"Direction":      {Line: 1, Column: 28, Length: 2, Height: 1},
		"Info_area_2":    {Line: 2, Column: 0, Length: 16, Height: 1},
		"Option_C_1":     {Line: 2, Column: 16, Length: 14, Height: 1},
		"Info_area_3":    {Line: 3, Column: 0, Length: 16, Height: 1},
		"Option_C_2":     {Line: 3, Column: 16, Length: 14, Height: 1},
		"System_name":    {Line: 4, Column: 0, Length: 24, Height: 1},
		"System_option":  {Line: 5, Column: 0, Length: 26, Height: 1},
		"System_avoid":   {Line: 5, Column: 26, Length: 4, Height: 1},
		"Dept_name":      {Line: 6, Column: 0, Length: 24, Height: 1},
		"Dept_option":    {Line: 7, Column: 0, Length: 26, Height: 1},
		"Dept_avoid":     {Line: 7, Column: 26, Length: 4, Height: 1},
		"Channel_name":   {Line: 8, Column: 0, Length: 24, Height: 1},
		"Channel_option": {Line: 9, Column: 0, Length: 26, Height: 1},
		"Channel_avoid":  {Line: 9, Column: 26, Length: 4, Height: 1},
		"Option_A_1":     {Line: 10, Column: 0, Length: 16, Height: 1},
		"Option_B_1":     {Line: 10, Column: 16, Length: 14, Height: 1},
		"Option_A_2":     {Line: 11, Column: 0, Length: 16, Height: 1},
		"Option_B_2":     {Line: 11, Column: 16, Length: 14, Height: 1},
		"Option_A_3":     {Line: 12, Column: 0, Length: 16, Height: 1},
		"Option_B_3":     {Line: 12, Column: 16, Length: 14, Height: 1},
		"Option_A_4":     {Line: 13, Column: 0, Length: 16, Height: 1},
		"Option_B_4":     {Line: 13, Column: 16, Length: 14, Height: 1},
		"Option_A_5":     {Line: 14, Column: 0, Length: 16, Height: 1},
		"Option_B_5":     {Line: 14, Column: 16, Length: 14, Height: 1},
		"Icon_1":         {Line: 15, Column: 0, Length: 3, Height: 1},
		"Icon_2":         {Line: 15, Column: 3, Length: 3, Height: 1},
		"Icon_3":         {Line: 15, Column: 6, Length: 3, Height: 1},
		"Icon_4":         {Line: 15, Column: 9, Length: 3, Height: 1},
		"Icon_5":         {Line: 15, Column: 12, Length: 3, Height: 1},
		"Icon_6":         {Line: 15, Column: 15, Length: 3, Height: 1},
		"Icon_7":         {Line: 15, Column: 18, Length: 3, Height: 1},
		"Icon_8":         {Line: 15, Column: 21, Length: 3, Height: 1},
		"Icon_9":         {Line: 15, Column: 24, Length: 3, Height: 1},
		"Icon_a":         {Line: 15, Column: 27, Length: 3, Height: 1},
	},
	"search": {
		"Func":             {Line: 0, Column: 0, Length: 2, Height: 1},
		"Option_1":         {Line: 0, Column: 2, Length: 6, Height: 1},
		"Option_2":         {Line: 0, Column: 8, Length: 6, Height: 1},
		"Option_3":         {Line: 0, Column: 14, Length: 6, Height: 1},
		"Option_4":         {Line: 0, Column: 20, Length: 6, Height: 1},
		"Signal_meter":     {Line: 0, Column: 26, Length: 2, Height: 1},
		"Battery":          {Line: 0, Column: 28, Length: 2, Height: 1},
		"Info_area_1":      {Line: 1, Column: 0, Length: 14, Height: 1},
		"Option_7":         {Line: 1, Column: 14, Length: 6, Height: 1},
		"Option_8":         {Line: 1, Column: 20, Length: 6, Height: 1},
		"Key_lock":         {Line: 1, Column: 26, Length: 2, Height: 1},
		"Direction":        {Line: 1, Column: 28, Length: 2, Height: 1},
		"Info_area_2":      {Line: 2, Column: 0, Length: 16, Height: 1},
		"Option_C_1":       {Line: 2, Column: 16, Length: 14, Height: 1},
		"Info_area_3":      {Line: 3, Column: 0, Length: 16, Height: 1},
		"Option_C_2":       {Line: 3, Column: 16, Length: 14, Height: 1},
		"Primary_area_1":   {Line: 4, Column: 0, Length: 24, Height: 1},
		"Primary_area_2":   {Line: 5, Column: 0, Length: 24, Height: 1},
		"Primary_area_3":   {Line: 6, Column: 0, Length: 24, Height: 1},
		"Sub_info_area":    {Line: 7, Column: 0, Length: 16, Height: 1},
		"Modulation":       {Line: 7, Column: 16, Length: 6, Height: 1},
		"Avoid":            {Line: 7, Column: 22, Length: 4, Height: 1},
		"Hold":             {Line: 7, Column: 26, Length: 4, Height: 1},
		"Mode_detail_area": {Line: 8, Column: 0, Length: 30, Height: 4},
		"Option_A_1":       {Line: 12, Column: 0, Length: 16, Height: 1},
		"Option_B_1":       {Line: 12, Column: 16, Length: 14, Height: 1},
		"Option_A_2":       {Line: 13, Column: 0, Length: 16, Height: 1},
		"Option_B_2":       {Line: 13, Column: 16, Length: 14, Height: 1},
		"Option_A_3":       {Line: 14, Column: 0, Length: 16, Height: 1},
		"Option_B_3":       {Line: 14, Column: 16, Length: 14, Height: 1},
		"Icon_1":           {Line: 15, Column: 0, Length: 3, Height: 1},
		"Icon_2":           {Line: 15, Column: 3, Length: 3, Height: 1},
		"Icon_3":           {Line: 15, Column: 6, Length: 3, Height: 1},
		"Icon_4":           {Line: 15, Column: 9, Length: 3, Height: 1},
		"Icon_5":           {Line: 15, Column: 12, Length: 3, Height: 1},
		"Icon_6":           {Line: 15, Column: 15, Length: 3, Height: 1},
		"Icon_7":           {Line: 15, Column: 18, Length: 3, Height: 1},
		"Icon_8":           {Line: 15, Column: 21, Length: 3, Height: 1},
		"Icon_9":           {Line: 15, Column: 24, Length: 3, Height: 1},
		"Icon_a":           {Line: 15, Column: 27, Length: 3, Height: 1},
	},
	"weather": {
		"Func":             {Line: 0, Column: 0, Length: 2, Height: 1},
		"Option_1":         {Line: 0, Column: 2, Length: 6, Height: 1},
		"Option_2":         {Line: 0, Column: 8, Length: 6, Height: 1},
		"Option_3":         {Line: 0, Column: 14, Length: 6, Height: 1},
		"Option_4":         {Line: 0, Column: 20, Length: 6, Height: 1},
		"Signal_meter":     {Line: 0, Column: 26, Length: 2, Height: 1},
		"Battery":          {Line: 0, Column: 28, Length: 2, Height: 1},
		"Info_area_1":      {Line: 1, Column: 0, Length: 14, Height: 1},
		"Option_7":         {Line: 1, Column: 14, Length: 6, Height: 1},
		"Option_8":         {Line: 1, Column: 20, Length: 6, Height: 1},
		"Key_lock":         {Line: 1, Column: 26, Length: 2, Height: 1},
		"Direction":        {Line: 1, Column: 28, Length: 2, Height: 1},
		"Info_area_2":      {Line: 2, Column: 0, Length: 16, Height: 1},
		"Option_C_1":       {Line: 2, Column: 16, Length: 14, Height: 1},
		"Info_area_3":      {Line: 3, Column: 0, Length: 16, Height: 1},
		"Option_C_2":       {Line: 3, Column: 16, Length: 14, Height: 1},
		"Primary_area_1":   {Line: 4, Column: 0, Length: 24, Height: 1},
		"Primary_area_2":   {Line: 5, Column: 0, Length: 24, Height: 1},
		"Primary_area_3":   {Line: 6, Column: 0, Length: 24, Height: 1},
		"Sub_info_area":    {Line: 7, Column: 0, Length: 16, Height: 1},
		"Modulation":       {Line: 7, Column: 16, Length: 6, Height: 1},
		"Avoid":            {Line: 7, Column: 22, Length: 4, Height: 1},
		"Hold":             {Line: 7, Column: 26, Length: 4, Height: 1},
		"Mode_detail_area": {Line: 8, Column: 0, Length: 30, Height: 4},
		"Option_A_1":       {Line: 12, Column: 0, Length: 16, Height: 1},
		"Option_B_1":       {Line: 12, Column: 16, Length: 14, Height: 1},
		"Option_A_2":       {Line: 13, Column: 0, Length: 16, Height: 1},
		"Option_B_2":       {Line: 13, Column: 16, Length: 14, Height: 1},
		"Option_A_3":       {Line: 14, Column: 0, Length: 16, Height: 1},
		"Option_B_3":       {Line: 14, Column: 16, Length: 14, Height: 1},
		"Icon_1":           {Line: 15, Column: 0, Length: 3, Height: 1},
		"Icon_2":           {Line: 15, Column: 3, Length: 3, Height: 1},
		"Icon_3":           {Line: 15, Column: 6, Length: 3, Height: 1},
		"Icon_4":           {Line: 15, Column: 9, Length: 3, Height: 1},
		"Icon_5":           {Line: 15, Column: 12, Length: 3, Height: 1},
		"Icon_6":           {Line: 15, Column: 15, Length: 3, Height: 1},
		"Icon_7":           {Line: 15, Column: 18, Length: 3, Height: 1},
		"Icon_8":           {Line: 15, Column: 21, Length: 3, Height: 1},
		"Icon_9":           {Line: 15, Column: 24, Length: 3, Height: 1},
		"Icon_a":           {Line: 15, Column: 27, Length: 3, Height: 1},
	},
	"tone-out": {
		"Func":             {Line: 0, Column: 0, Length: 2, Height: 1},
		"Option_1":         {Line: 0, Column: 2, Length: 6, Height: 1},
		"Option_2":         {Line: 0, Column: 8, Length: 6, Height: 1},
		"Option_3":         {Line: 0, Column: 14, Length: 6, Height: 1},
		"Option_4":         {Line: 0, Column: 20, Length: 6, Height: 1},
		"Signal_meter":     {Line: 0, Column: 26, Length: 2, Height: 1},
		"Battery":          {Line: 0, Column: 28, Length: 2, Height: 1},
		"Info_area_1":      {Line: 1, Column: 0, Length: 14, Height: 1},
		"Option_7":         {Line: 1, Column: 14, Length: 6, Height: 1},
		"Option_8":         {Line: 1, Column: 20, Length: 6, Height: 1},
		"Key_lock":         {Line: 1, Column: 26, Length: 2, Height: 1},
		"Direction":        {Line: 1, Column: 28, Length: 2, Height: 1},
		"Info_area_2":      {Line: 2, Column: 0, Length: 16, Height: 1},
		"Option_C_1":       {Line: 2, Column: 16, Length: 14, Height: 1},
		"Info_area_3":      {Line: 3, Column: 0, Length: 16, Height: 1},
		"Option_C_2":       {Line: 3, Column: 16, Length: 14, Height: 1},
		"Primary_area_1":   {Line: 4, Column: 0, Length: 24, Height: 1},
		"Primary_area_2":   {Line: 5, Column: 0, Length: 24, Height: 1},
		"Primary_area_3":   {Line: 6, Column: 0, Length: 24, Height: 1},
		"Sub_info_area":    {Line: 7, Column: 0, Length: 16, Height: 1},
		"Modulation":       {Line: 7, Column: 16, Length: 6, Height: 1},
		"Avoid":            {Line: 7, Column: 22, Length: 4, Height: 1},
		"Hold":             {Line: 7, Column: 26, Length: 4, Height: 1},
		"Mode_detail_area": {Line: 8, Column: 0, Length: 30, Height: 4},
		"Option_A_1":       {Line: 12, Column: 0, Length: 16, Height: 1},
		"Option_B_1":       {Line: 12, Column: 16, Length: 14, Height: 1},
		"Option_A_2":       {Line: 13, Column: 0, Length: 16, Height: 1},
		"Option_B_2":       {Line: 13, Column: 16, Length: 14, Height: 1},
		"Option_A_3":       {Line: 14, Column: 0, Length: 16, Height: 1},
		"Option_B_3":       {Line: 14, Column: 16, Length: 14, Height: 1},
		"Icon_1":           {Line: 15, Column: 0, Length: 3, Height: 1},
		"Icon_2":           {Line: 15, Column: 3, Length: 3, Height: 1},
		"Icon_3":           {Line: 15, Column: 6, Length: 3, Height: 1},
		"Icon_4":           {Line: 15, Column: 9, Length: 3, Height: 1},
		"Icon_5":           {Line: 15, Column: 12, Length: 3, Height: 1},
		"Icon_6":           {Line: 15, Column: 15, Length: 3, Height: 1},
		"Icon_7":           {Line: 15, Column: 18, Length: 3, Height: 1},
		"Icon_8":           {Line: 15, Column: 21, Length: 3, Height: 1},
		"Icon_9":           {Line: 15, Column: 24, Length: 3, Height: 1},
		"Icon_a":           {Line: 15, Column: 27, Length: 3, Height: 1},
	},
}

// areaOrder is the order the knob steps through each layout's areas, which is
// the order the editor's own menu lists them in.
//
// It is here to save time rather than to be trusted. The editor draws the
// layout's artwork rather than a list of names, so the only way to know which
// area the knob is on is to open it and read its title, and doing that for
// every area on the way to the seventeenth is most of the cost of setting a
// color. Knowing the order means stepping straight there and opening one menu
// to check, instead of opening seventeen.
//
// Anything using this checks where it landed and falls back to walking by name
// when the answer is not what this expects, so a firmware that reorders or
// inserts an area costs time rather than correctness.
var areaOrder = map[string][]string{
	"simple-conventional": {
		"Func", "Option_1", "Option_2", "Option_3", "Option_4", "Signal_meter",
		"Battery", "Space_0", "Option_5", "Option_6", "Option_7", "Option_8",
		"Key_lock", "Direction", "System_name", "System_option", "System_avoid",
		"Dept_name", "Dept_option", "Dept_avoid", "Channel_name",
		"Channel_option", "Channel_avoid", "Option_A", "Option_B", "Icon_1",
		"Icon_2", "Icon_3", "Icon_4", "Icon_5", "Icon_6", "Icon_7", "Icon_8",
		"Icon_9", "Icon_a", "Soft1_key", "Space_1", "Soft2_key", "Space_2",
		"Soft3_key",
	},
	"simple-trunk": {
		"Func", "Option_1", "Option_2", "Option_3", "Option_4", "Signal_meter",
		"Battery", "Space_0", "Option_5", "Option_6", "Option_7", "Option_8",
		"Key_lock", "Direction", "System_name", "System_option", "System_avoid",
		"Dept_name", "Dept_option", "Dept_avoid", "Channel_name",
		"Channel_option", "Channel_avoid", "Option_A", "Option_B", "Icon_1",
		"Icon_2", "Icon_3", "Icon_4", "Icon_5", "Icon_6", "Icon_7", "Icon_8",
		"Icon_9", "Icon_a", "Soft1_key", "Space_1", "Soft2_key", "Space_2",
		"Soft3_key",
	},
	"detail-conventional": {
		"Func", "Option_1", "Option_2", "Option_3", "Option_4", "Signal_meter",
		"Battery", "Info_area_1", "Option_7", "Option_8", "Key_lock",
		"Direction", "Info_area_2", "Option_C_1", "Info_area_3", "Option_C_2",
		"System_name", "System_option", "System_avoid", "Dept_name",
		"Dept_option", "Dept_avoid", "Channel_name", "Channel_option",
		"Channel_avoid", "Option_A_1", "Option_B_1", "Option_A_2", "Option_B_2",
		"Option_A_3", "Option_B_3", "Option_A_4", "Option_B_4", "Option_A_5",
		"Option_B_5", "Icon_1", "Icon_2", "Icon_3", "Icon_4", "Icon_5", "Icon_6",
		"Icon_7", "Icon_8", "Icon_9", "Icon_a", "Soft1_key", "Space_1",
		"Soft2_key", "Space_2", "Soft3_key",
	},
	"detail-trunk": {
		"Func", "Option_1", "Option_2", "Option_3", "Option_4", "Signal_meter",
		"Battery", "Info_area_1", "Option_7", "Option_8", "Key_lock",
		"Direction", "Info_area_2", "Option_C_1", "Info_area_3", "Option_C_2",
		"System_name", "System_option", "System_avoid", "Dept_name",
		"Dept_option", "Dept_avoid", "Channel_name", "Channel_option",
		"Channel_avoid", "Option_A_1", "Option_B_1", "Option_A_2", "Option_B_2",
		"Option_A_3", "Option_B_3", "Option_A_4", "Option_B_4", "Option_A_5",
		"Option_B_5", "Icon_1", "Icon_2", "Icon_3", "Icon_4", "Icon_5", "Icon_6",
		"Icon_7", "Icon_8", "Icon_9", "Icon_a", "Soft1_key", "Space_1",
		"Soft2_key", "Space_2", "Soft3_key",
	},
	"search": {
		"Func", "Option_1", "Option_2", "Option_3", "Option_4", "Signal_meter",
		"Battery", "Info_area_1", "Option_7", "Option_8", "Key_lock",
		"Direction", "Info_area_2", "Option_C_1", "Info_area_3", "Option_C_2",
		"Primary_area_1", "Primary_area_2", "Primary_area_3", "Sub_info_area",
		"Modulation", "Avoid", "Hold", "Mode_detail_area", "Option_A_1",
		"Option_B_1", "Option_A_2", "Option_B_2", "Option_A_3", "Option_B_3",
		"Icon_1", "Icon_2", "Icon_3", "Icon_4", "Icon_5", "Icon_6", "Icon_7",
		"Icon_8", "Icon_9", "Icon_a", "Soft1_key", "Space_1", "Soft2_key",
		"Space_2", "Soft3_key",
	},
	"weather": {
		"Func", "Option_1", "Option_2", "Option_3", "Option_4", "Signal_meter",
		"Battery", "Info_area_1", "Option_7", "Option_8", "Key_lock",
		"Direction", "Info_area_2", "Option_C_1", "Info_area_3", "Option_C_2",
		"Primary_area_1", "Primary_area_2", "Primary_area_3", "Sub_info_area",
		"Modulation", "Avoid", "Hold", "Mode_detail_area", "Option_A_1",
		"Option_B_1", "Option_A_2", "Option_B_2", "Option_A_3", "Option_B_3",
		"Icon_1", "Icon_2", "Icon_3", "Icon_4", "Icon_5", "Icon_6", "Icon_7",
		"Icon_8", "Icon_9", "Icon_a", "Soft1_key", "Space_1", "Soft2_key",
		"Space_2", "Soft3_key",
	},
	"tone-out": {
		"Func", "Option_1", "Option_2", "Option_3", "Option_4", "Signal_meter",
		"Battery", "Info_area_1", "Option_7", "Option_8", "Key_lock",
		"Direction", "Info_area_2", "Option_C_1", "Info_area_3", "Option_C_2",
		"Primary_area_1", "Primary_area_2", "Primary_area_3", "Sub_info_area",
		"Modulation", "Avoid", "Hold", "Mode_detail_area", "Option_A_1",
		"Option_B_1", "Option_A_2", "Option_B_2", "Option_A_3", "Option_B_3",
		"Icon_1", "Icon_2", "Icon_3", "Icon_4", "Icon_5", "Icon_6", "Icon_7",
		"Icon_8", "Icon_9", "Icon_a", "Soft1_key", "Space_1", "Soft2_key",
		"Space_2", "Soft3_key",
	},
}
