// Copyright 2026 Alan Beebe (radiocli.com). All Rights Reserved.
// Author: Alan Beebe
// Created: 8/16/2026

package update

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"net/http"
	"os"
	"strconv"
	"strings"
	"testing"
)

// failingReader reports a failure partway through, which is what a connection
// dropping mid-download looks like from here.
type failingReader struct{ left int }

// Read hands back a few bytes and then fails.
//
// Parameters:
//   - p: the buffer to fill
//
// Returns:
//   - how many bytes were written, and an error once the allowance is spent
func (f *failingReader) Read(p []byte) (int, error) {
	if f.left <= 0 {
		return 0, errors.New("the connection dropped")
	}
	n := min(f.left, len(p))
	f.left -= n
	return n, nil
}

// shrink lowers the download caps for the length of a test, so a limit can be
// proved without producing tens of megabytes to do it.
//
// Parameters:
//   - t: the test the change is tied to
//   - archive: the archive cap to use
//   - binary: the extracted program cap to use
func shrink(t *testing.T, archive, binary int64) {
	t.Helper()

	wasArchive, wasBinary := maxArchiveBytes, maxBinaryBytes
	maxArchiveBytes, maxBinaryBytes = archive, binary
	t.Cleanup(func() { maxArchiveBytes, maxBinaryBytes = wasArchive, wasBinary })
}

// sha256Of is what a body should hash to, for a test that wants to assert on
// the digest rather than recompute it by hand.
//
// Parameters:
//   - body: the bytes to hash
//
// Returns:
//   - the SHA-256 as hex
func sha256Of(body string) string {
	sum := sha256.Sum256([]byte(body))
	return hex.EncodeToString(sum[:])
}

// Test_checksumFor tests finding one file's checksum in a checksums file.
//
// Coverage: 100% (5 test cases covering every branch)
//
// Test cases:
//   - Found: the ordinary two-column line
//   - BinaryMarker: a name marked with a star, as binary mode writes it
//   - SkipsNoise: blank lines, comments and carriage returns are ignored
//   - ShortLine: a line with only one column is skipped rather than read
//   - Missing: a name the file does not list
func Test_checksumFor(t *testing.T) {
	file := []byte("# generated by the release workflow\n\n" +
		"aaaa  radiocli-mac.zip\r\n" +
		"bbbb  *radiocli-linux.tar.gz\n" +
		"orphan\n")

	// Verify the ordinary case, a name matched in the second column
	t.Run("Found", func(t *testing.T) {
		got, err := checksumFor(file, "radiocli-mac.zip")
		if err != nil {
			t.Fatalf("expected no error, got: %v", err)
		}
		if got != "aaaa" {
			t.Errorf("expected aaaa, got: %q", got)
		}
	})

	// Verify that the star some tools put before a name is not treated as part
	// of it
	t.Run("BinaryMarker", func(t *testing.T) {
		got, err := checksumFor(file, "radiocli-linux.tar.gz")
		if err != nil || got != "bbbb" {
			t.Errorf("expected bbbb, got: %q %v", got, err)
		}
	})

	// Verify that comments, blank lines and carriage returns do not stop the
	// file being read
	t.Run("SkipsNoise", func(t *testing.T) {
		if _, err := checksumFor(file, "radiocli-mac.zip"); err != nil {
			t.Errorf("expected the noise to be skipped, got: %v", err)
		}
	})

	// Verify that a line with nothing in the second column is skipped
	t.Run("ShortLine", func(t *testing.T) {
		if _, err := checksumFor(file, "orphan"); err == nil {
			t.Error("expected a one-column line not to match a name")
		}
	})

	// Verify that a name the file does not carry is refused, and that the
	// message says nothing was installed
	t.Run("Missing", func(t *testing.T) {
		_, err := checksumFor(file, "radiocli-windows.zip")
		if err == nil {
			t.Fatal("expected a missing name to be refused")
		}
		if !strings.Contains(err.Error(), "nothing was installed") {
			t.Errorf("expected the message to say nothing was installed, got: %v", err)
		}
	})
}

// Test_download tests streaming a release file to disk while hashing it.
//
// Coverage: 100% (6 test cases covering every branch)
//
// Test cases:
//   - Streams: the file lands on disk and the hash matches its contents
//   - NoStagingDirectory: a directory that cannot be staged in
//   - Unreachable: the request could not be made
//   - Refused: the server answered with a status
//   - Interrupted: the connection dropped partway through
//   - TooLarge: more arrived than any release is
//   - WrongSize: less arrived than the release said there was
func Test_download(t *testing.T) {
	body := "a release archive"

	// Verify the ordinary case: the bytes land beside the program and the
	// digest describes what was actually written
	t.Run("Streams", func(t *testing.T) {
		server := serve(t, func(w http.ResponseWriter, r *http.Request) {
			_, _ = w.Write([]byte(body))
		})
		dir := t.TempDir()

		path, digest, size, err := download(context.Background(),
			releaseAsset{Name: "a", URL: server.URL, Size: int64(len(body))}, dir)
		if err != nil {
			t.Fatalf("expected no error, got: %v", err)
		}
		if digest != sha256Of(body) {
			t.Errorf("expected the digest of the body, got: %q", digest)
		}
		if size != int64(len(body)) {
			t.Errorf("expected %d bytes, got: %d", len(body), size)
		}

		written, err := os.ReadFile(path)
		if err != nil || string(written) != body {
			t.Errorf("expected the body on disk, got: %q %v", written, err)
		}
	})

	// Verify that a directory which cannot be staged in fails before anything
	// is fetched
	t.Run("NoStagingDirectory", func(t *testing.T) {
		_, _, _, err := download(context.Background(), releaseAsset{}, "/no/such/place")
		if err == nil || !strings.Contains(err.Error(), "staging") {
			t.Errorf("expected staging to fail, got: %v", err)
		}
	})

	// Verify that a request which cannot be made is reported
	t.Run("Unreachable", func(t *testing.T) {
		server := serve(t, func(w http.ResponseWriter, r *http.Request) {})
		server.Close()

		if _, _, _, err := download(context.Background(),
			releaseAsset{URL: server.URL}, t.TempDir()); err == nil {
			t.Error("expected a closed server to fail the download")
		}
	})

	// Verify that a refusal is reported rather than saved as the archive
	t.Run("Refused", func(t *testing.T) {
		server := serve(t, func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusNotFound)
		})

		_, _, _, err := download(context.Background(),
			releaseAsset{URL: server.URL}, t.TempDir())
		if err == nil || !strings.Contains(err.Error(), "404") {
			t.Errorf("expected the status to be reported, got: %v", err)
		}
	})

	// Verify that a connection dropping partway through is a failure rather
	// than a short file that looks complete
	t.Run("Interrupted", func(t *testing.T) {
		server := serve(t, func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Length", strconv.Itoa(len(body)+50))
			_, _ = w.Write([]byte(body))
		})

		_, _, _, err := download(context.Background(),
			releaseAsset{Name: "a", URL: server.URL}, t.TempDir())
		if err == nil || !strings.Contains(err.Error(), "downloading") {
			t.Errorf("expected the interrupted download to be reported, got: %v", err)
		}
	})

	// Verify that a body larger than any release is refused rather than read to
	// the end
	t.Run("TooLarge", func(t *testing.T) {
		shrink(t, 4, 4)
		server := serve(t, func(w http.ResponseWriter, r *http.Request) {
			_, _ = w.Write([]byte(body))
		})

		_, _, _, err := download(context.Background(),
			releaseAsset{Name: "a", URL: server.URL}, t.TempDir())
		if err == nil || !strings.Contains(err.Error(), "larger than") {
			t.Errorf("expected the cap to refuse it, got: %v", err)
		}
	})

	// Verify that a file which does not match the size GitHub published is
	// refused, which catches a truncated download the cap would not
	t.Run("WrongSize", func(t *testing.T) {
		server := serve(t, func(w http.ResponseWriter, r *http.Request) {
			_, _ = w.Write([]byte(body))
		})

		_, _, _, err := download(context.Background(),
			releaseAsset{Name: "a", URL: server.URL, Size: 9999}, t.TempDir())
		if err == nil || !strings.Contains(err.Error(), "did not finish") {
			t.Errorf("expected the size mismatch to be reported, got: %v", err)
		}
	})
}

// Test_fetchChecksums tests downloading the file every release is checked
// against.
//
// Coverage: 100% (5 test cases covering every branch)
//
// Test cases:
//   - Fetches: the file comes back as published
//   - NotPublished: a release without one is refused rather than trusted
//   - Unreachable: the request could not be made
//   - Refused: the server answered with a status
//   - TooLarge: a body far larger than a checksums file
func Test_fetchChecksums(t *testing.T) {
	// Verify that the published file is returned as it stands
	t.Run("Fetches", func(t *testing.T) {
		server := serve(t, func(w http.ResponseWriter, r *http.Request) {
			_, _ = w.Write([]byte("aaaa  radiocli-mac.zip\n"))
		})
		rel := release{Assets: []releaseAsset{{Name: checksumsAsset, URL: server.URL}}}

		got, err := fetchChecksums(context.Background(), rel)
		if err != nil {
			t.Fatalf("expected no error, got: %v", err)
		}
		if !strings.Contains(string(got), "radiocli-mac.zip") {
			t.Errorf("expected the checksums file, got: %q", got)
		}
	})

	// Verify that a release publishing no checksums is refused. This is the
	// decision the whole command rests on, so it is the one worth pinning down.
	t.Run("NotPublished", func(t *testing.T) {
		_, err := fetchChecksums(context.Background(), release{TagName: "v0.9.0"})
		if err == nil {
			t.Fatal("expected a release with no checksums to be refused")
		}
		for _, want := range []string{"v0.9.0", checksumsAsset, "nothing was installed"} {
			if !strings.Contains(err.Error(), want) {
				t.Errorf("expected %q in the message, got: %v", want, err)
			}
		}
	})

	// Verify that a request which cannot be made is reported
	t.Run("Unreachable", func(t *testing.T) {
		server := serve(t, func(w http.ResponseWriter, r *http.Request) {})
		server.Close()
		rel := release{Assets: []releaseAsset{{Name: checksumsAsset, URL: server.URL}}}

		if _, err := fetchChecksums(context.Background(), rel); err == nil {
			t.Error("expected a closed server to fail the fetch")
		}
	})

	// Verify that a refusal is reported
	t.Run("Refused", func(t *testing.T) {
		server := serve(t, func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusForbidden)
		})
		rel := release{Assets: []releaseAsset{{Name: checksumsAsset, URL: server.URL}}}

		if _, err := fetchChecksums(context.Background(), rel); err == nil {
			t.Error("expected the refusal to be reported")
		}
	})

	// Verify that something far too large to be a checksums file is refused
	t.Run("TooLarge", func(t *testing.T) {
		server := serve(t, func(w http.ResponseWriter, r *http.Request) {
			_, _ = w.Write([]byte(strings.Repeat("x", maxChecksumsBytes+1)))
		})
		rel := release{Assets: []releaseAsset{{Name: checksumsAsset, URL: server.URL}}}

		_, err := fetchChecksums(context.Background(), rel)
		if err == nil || !strings.Contains(err.Error(), checksumsAsset) {
			t.Errorf("expected an oversized file to be refused, got: %v", err)
		}
	})
}

// Test_readCapped tests reading up to a limit.
//
// Coverage: 100% (3 test cases covering every branch)
//
// Test cases:
//   - Reads: everything under the limit comes back
//   - TooLarge: going past the limit is reported rather than truncated
//   - Fails: a reader that errors
func Test_readCapped(t *testing.T) {
	// Verify that a body within the limit is returned whole
	t.Run("Reads", func(t *testing.T) {
		got, err := readCapped(strings.NewReader("hello"), 16)
		if err != nil || string(got) != "hello" {
			t.Errorf("expected hello, got: %q %v", got, err)
		}
	})

	// Verify that going past the limit is an error rather than a quietly
	// shortened result, which would otherwise look like a valid small file
	t.Run("TooLarge", func(t *testing.T) {
		_, err := readCapped(strings.NewReader("hello"), 2)
		if err == nil || !strings.Contains(err.Error(), "larger than") {
			t.Errorf("expected the limit to be enforced, got: %v", err)
		}
	})

	// Verify that a read failure is passed on
	t.Run("Fails", func(t *testing.T) {
		if _, err := readCapped(&failingReader{}, 16); err == nil {
			t.Error("expected the read failure to be reported")
		}
	})
}

// Test_verify tests checking a download against what the release published.
//
// Coverage: 100% (5 test cases covering every branch)
//
// Test cases:
//   - Matches: the checksum agrees, and GitHub's own hash agrees too
//   - NoGitHubDigest: an older release carrying no digest still verifies
//   - NotListed: the checksums file does not name this file
//   - Mismatch: the download hashes to something else
//   - DisagreesWithGitHub: the checksums file and GitHub do not agree
func Test_verify(t *testing.T) {
	want := asset{archive: "radiocli-mac.zip"}
	digest := sha256Of("the archive")
	sums := []byte(digest + "  radiocli-mac.zip\n")

	// Verify the ordinary case, where both opinions agree with the file
	t.Run("Matches", func(t *testing.T) {
		from := releaseAsset{Digest: "sha256:" + digest}
		if err := verify(want, from, sums, digest); err != nil {
			t.Errorf("expected no error, got: %v", err)
		}
	})

	// Verify that a release from before GitHub recorded digests still verifies
	// against the checksums file alone
	t.Run("NoGitHubDigest", func(t *testing.T) {
		if err := verify(want, releaseAsset{}, sums, digest); err != nil {
			t.Errorf("expected no error, got: %v", err)
		}
	})

	// Verify that a checksums file which does not name this archive is refused
	t.Run("NotListed", func(t *testing.T) {
		other := asset{archive: "radiocli-windows.zip"}
		if err := verify(other, releaseAsset{}, sums, digest); err == nil {
			t.Error("expected an unlisted archive to be refused")
		}
	})

	// Verify that a download hashing to something else is refused, and that the
	// message gives both hashes and the two things that cause it
	t.Run("Mismatch", func(t *testing.T) {
		err := verify(want, releaseAsset{}, sums, sha256Of("something else"))
		if err == nil {
			t.Fatal("expected a mismatch to be refused")
		}
		for _, phrase := range []string{"nothing was installed", "corrupted", digest} {
			if !strings.Contains(err.Error(), phrase) {
				t.Errorf("expected %q in the message, got: %v", phrase, err)
			}
		}
	})

	// Verify that a release disagreeing with itself is refused. This is what
	// catches a checksums file generated from a different build than the one
	// published beside it.
	t.Run("DisagreesWithGitHub", func(t *testing.T) {
		from := releaseAsset{Digest: "sha256:" + sha256Of("a third thing")}
		err := verify(want, from, sums, digest)
		if err == nil || !strings.Contains(err.Error(), "GitHub recorded") {
			t.Errorf("expected the disagreement to be refused, got: %v", err)
		}
	})
}
